### PR TITLE
Twitter client/tidy up

### PR DESCRIPTION
**Pull request by raquel-ucl**
Older changes in #10 have just been merged although they didn't work. I'll continue here.

### CODE REVIEW

**Comment by lili2311** [comment]
:+1:

**Comment by raquel-ucl** [comment]
Some #helloworld tweets there:

screen shot 2016-04-09 at 15 54 25

**Comment by raquel-ucl** [comment]
I'll work on the date stuff in this branch as well. I should be able to do something like this:

tweepy.Cursor(api.search,q='test',since='2015-06-26 10:01:25')

To get the date, I could look into the newest tweet, or the front end needs to work out the time and pass it  as a parameter to the django-admin command. What do you think is best @lili2311?

**Comment by lili2311** [comment]
What if we store the `created at` date of the tweets as well? Then on every run we get the latest tweet we have stored and it's created date and use that date as `since`.

**Comment by raquel-ucl** [comment]
Yeah, I like that. Will do tonight.

**Comment by raquel-ucl** [comment]
Should we merge what we have so far? It doesn't work with the dates yet, but it's callable and inserts tweets in the DB so you can play with the frontend.

**Pull request merged**
